FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine AS production

WORKDIR /app

COPY --from=builder /app/package*.json ./

RUN npm install --only=production

COPY --from=builder /app/dist ./dist/

# Проверяем структуру dist
RUN ls -la /app/dist/ && ls -la /app/dist/src/

EXPOSE 3000

CMD ["node", "dist/src/main.js"]