name: Build and Push Docker Image

on:
  push:
    branches: ['review-3']
  pull_request:
    branches: ['review-3']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: |
          echo "REPO=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPO }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: 'ghcr.io/${{ env.REPO }}/film-backend:latest'

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: 'ghcr.io/${{ env.REPO }}/film-frontend:latest'

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: 'ghcr.io/${{ env.REPO }}/film-nginx:latest'
